# Generated by Django 6.0.2 on 2026-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='searchlog',
            name='browser',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='device',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='os',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user_ip',
            field=models.CharField(default='0.0.0.0', max_length=100),
            preserve_default=False,
        ),
    ]
