# Generated by Django 6.0.2 on 2026-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_searchlog_options_searchlog_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='country',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
